In [2]:
# try:
import numpy
import pandas as pd
import pickle as pk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import re
from nltk.stem.snowball import SnowballStemmer
import nltk
stemmer = SnowballStemmer("english")
import numpy
import pandas as pd
import pickle as pk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import re
from nltk.stem.snowball import SnowballStemmer
import nltk
stemmer = SnowballStemmer("english")
print('Done!')

Done!


In [3]:
#Input abstract
ARTICLE_READ=""" Statistical modeling of experimental physical laws is based on the
probability density function of measured variables. It is expressed by experimental 
data via a kernel estimator. The kernel is determined objectively
by the scattering of data during calibration of experimental setup. A physical
law, which relates measured variables, is optimally extracted from experimental
data by the conditional average estimator. It is derived directly from the
kernel estimator and corresponds to a general nonparametric regression. The
proposed method is demonstrated by the modeling of a return map of noisy
chaotic data. In this example, the nonparametric regression is used to predict
a future value of chaotic time series from the present one. The mean predictor
error is used in the definition of predictor quality, while the redundancy is
expressed by the mean square distance between data points. Both statistics are
used in a new definition of predictor cost function. From the minimum of the
predictor cost function, a proper number of data in the model is estimated.
"""

In [4]:
RES_ARTICLES="D:\Mini_project\Research_article_recommendation_system\data\project_data.csv"
# ARTICLE_READ=[1,10]
NUM_RECOMMENDED_ARTICLES=5

In [5]:
res_articles = pd.read_csv(RES_ARTICLES,encoding='utf-8',index_col=0)
#drop all the unnamed columns
res_articles.drop(res_articles.columns[res_articles.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
res_articles.head()

submitter  \
id                              
0704.0001      Pavel Nadolsky   
0704.0002        Louis Theran   
0704.0003         Hongjun Pan   
0704.0004        David Callan   
0704.0005  Alberto Torchinsky   

                                                     authors  \
id                                                             
0704.0001  C. Bal\'azs, E. L. Berger, P. M. Nadolsky, C.-...   
0704.0002                    Ileana Streinu and Louis Theran   
0704.0003                                        Hongjun Pan   
0704.0004                                       David Callan   
0704.0005           Wael Abu-Shammala and Alberto Torchinsky   

                                                       title  \
id                                                             
0704.0001  Calculation of prompt diphoton production cros...   
0704.0002           Sparsity-certifying Graph Decompositions   
0704.0003  The evolution of the Earth-Moon system based o...   
0704.0004  A determinant of Stirling cycle numbers counts...   
0704.0005  From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...   

                                          comments  \
id                                                   
0704.0001  37 pages, 15 figures; published version   
0704.0002    To appear in Graphs and Combinatorics   
0704.0003                      23 pages, 3 figures   
0704.0004                                 11 pages   
0704.0005                                      NaN   

                                         journal-ref  \
id                                                     
0704.0001                   Phys.Rev.D76:013009,2007   
0704.0002                                        NaN   
0704.0003                                        NaN   
0704.0004                                        NaN   
0704.0005  Illinois J. Math. 52 (2008) no.2, 681-689   

                                  doi         report-no       categories  \
id                                                                         
0704.0001  10.1103/PhysRevD.76.013009  ANL-HEP-PR-07-12           hep-ph   
0704.0002                         NaN               NaN    math.CO cs.CG   
0704.0003                         NaN               NaN   physics.gen-ph   
0704.0004                         NaN               NaN          math.CO   
0704.0005                         NaN               NaN  math.CA math.FA   

                                                     license  \
id                                                             
0704.0001                                                NaN   
0704.0002  http://arxiv.org/licenses/nonexclusive-distrib...   
0704.0003                                                NaN   
0704.0004                                                NaN   
0704.0005                                                NaN   

                                                    abstract  ...  \
id                                                            ...   
0704.0001    A fully differential calculation in perturba...  ...   
0704.0002    We describe a new algorithm, the $(k,\ell)$-...  ...   
0704.0003    The evolution of Earth-Moon system is descri...  ...   
0704.0004    We show that a determinant of Stirling cycle...  ...   
0704.0005    In this paper we show how to compute the $\L...  ...   

          authors_parsed/17/3 authors_parsed/18/3 authors_parsed/19/3  \
id                                                                      
0704.0001                 NaN                 NaN                 NaN   
0704.0002                 NaN                 NaN                 NaN   
0704.0003                 NaN                 NaN                 NaN   
0704.0004                 NaN                 NaN                 NaN   
0704.0005                 NaN                 NaN                 NaN   

          authors_parsed/20/3 authors_parsed/21/3 authors_parsed/22/3  \
id                                                                 

In [10]:
res_ids = res_articles['id'].tolist()
res_articles = res_articles[['title','abstract']].dropna()
#articles is a list of all articles
articles = res_articles['abstract'].tolist()
articles[0] #an uncleaned article

KeyError: 'id'

In [7]:
res_ids

NameError: name 'res_ids' is not defined

In [ ]:
def clean_text(document):
    document = re.sub('[^\w_\s-]', ' ',document)       #remove punctuation marks and other symbols
    tokens = nltk.word_tokenize(document)              #Tokenize sentences
    cleaned_article = ' '.join([stemmer.stem(item) for item in tokens])    #Stemming each token
    return cleaned_article

In [ ]:
cleaned_articles = list(map(clean_text, articles))
cleaned_articles[0]  #a cleaned, tokenized and stemmed article

'a fulli differenti calcul in perturb quantum chromodynam is present for the product of massiv photon pair at hadron collid all next-to-lead order perturb contribut from quark-antiquark gluon- anti quark and gluon-gluon subprocess are includ as well as all-ord resumm of initial-st gluon radiat valid at next-to-next-to-lead logarithm accuraci the region of phase space is specifi in which the calcul is most reliabl good agreement is demonstr with data from the fermilab tevatron and predict are made for more detail test with cdf and do data predict are shown for distribut of diphoton pair produc at the energi of the larg hadron collid lhc distribut of the diphoton pair from the decay of a higg boson are contrast with those produc from qcd process at the lhc show that enhanc sensit to the signal can be obtain with judici select of event'

In [ ]:
user_articles = clean_text(ARTICLE_READ)
user_articles

'statist model of experiment physic law is base on the probabl densiti function of measur variabl it is express by experiment data via a kernel estim the kernel is determin object by the scatter of data dure calibr of experiment setup a physic law which relat measur variabl is optim extract from experiment data by the condit averag estim it is deriv direct from the kernel estim and correspond to a general nonparametr regress the propos method is demonstr by the model of a return map of noisi chaotic data in this exampl the nonparametr regress is use to predict a futur valu of chaotic time seri from the present one the mean predictor error is use in the definit of predictor qualiti while the redund is express by the mean squar distanc between data point both statist are use in a new definit of predictor cost function from the minimum of the predictor cost function a proper number of data in the model is estim'

In [ ]:
#Generate tfidf matrix model for entire corpus
tfidf_matrix = TfidfVectorizer(stop_words='english', min_df=2) 
# min_df : When building the vocabulary ignore terms that have a document frequency strictly lower than the given threshold
article_tfidf_matrix = tfidf_matrix.fit_transform(cleaned_articles)
article_tfidf_matrix #tfidf vector of an article

<1918x4965 sparse matrix of type '<class 'numpy.float64'>'
	with 96335 stored elements in Compressed Sparse Row format>

In [ ]:
#Generate tfidf matrix model for read articles
user_article_tfidf_vector = tfidf_matrix.transform([user_articles])
user_article_tfidf_vector

<1x4965 sparse matrix of type '<class 'numpy.float64'>'
	with 61 stored elements in Compressed Sparse Row format>

In [ ]:
user_article_tfidf_vector.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
articles_similarity_score=cosine_similarity(article_tfidf_matrix, user_article_tfidf_vector)

In [ ]:
articles_similarity_score

array([[0.04018047],
       [0.01733515],
       [0.04887974],
       ...,
       [0.05149971],
       [0.07339802],
       [0.04162327]])

In [ ]:
recommended_articles_id = articles_similarity_score.flatten().argsort()[::-1]
recommended_articles_id

array([  97,  661,  141, ...,  369,  804, 1171], dtype=int64)

In [ ]:
#Remove read articles from recommendations
final_recommended_articles_id = [article_id for article_id in recommended_articles_id][:NUM_RECOMMENDED_ARTICLES]
final_recommended_articles_id

[97, 661, 141, 152, 1862]

In [ ]:
# print ('Recommendations ')
# print (res_articles.loc[final_recommended_articles_id]['title'])

Recommendations 


KeyError: "None of [Int64Index([97, 661, 141, 152, 1862], dtype='int64', name='id')] are in the [index]"